### ISSUE TITLE
Format the Instant by custom pattern not working

### ISSUE THREAD

**Issue by jdkcn** [thymeleaf/thymeleaf-extras-java8time#17]
In template file:

```html
<span th:text="${#temporals.format(#authentication.principal.createTime, 'yyyy-MM-dd')}" th:remove="tag">2017-08-24</span>
```
The exception:
```

org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "class path resource [templates/workbench.html]")
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
Caused by: org.attoparser.ParseException: Error formatting date for locale zh_CN (template: "layout" - line 145, col 45)
	at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:393) ~[attoparser-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:230) ~[thymeleaf-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	... 99 common frames omitted
Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Error formatting date for locale zh_CN (template: "layout" - line 145, col 45)
	at org.thymeleaf.extras.java8time.util.TemporalFormattingUtils.formatDate(TemporalFormattingUtils.java:186) ~[thymeleaf-extras-java8time-3.0.1.RELEASE.jar:3.0.1.RELEASE]
	... 101 common frames omitted
Caused by: java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: Year
	at java.time.Instant.getLong(Instant.java:603) ~[na:1.8.0_74]
	at java.time.format.DateTimePrintContext.getValue(DateTimePrintContext.java:298) ~[na:1.8.0_74]
	at java.time.format.DateTimeFormatterBuilder$NumberPrinterParser.format(DateTimeFormatterBuilder.java:2540) ~[na:1.8.0_74]
	at java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2179) ~[na:1.8.0_74]
	at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1746) ~[na:1.8.0_74]
	at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1720) ~[na:1.8.0_74]
	at org.thymeleaf.extras.java8time.util.TemporalFormattingUtils.formatDate(TemporalFormattingUtils.java:183) ~[thymeleaf-extras-java8time-3.0.1.RELEASE.jar:3.0.1.RELEASE]
	... 144 common frames omitted

2017-08-24 15:39:29.211 ERROR 2112 --- [nio-8080-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "class path resource [templates/workbench.html]")] with root cause

java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: Year
	at java.time.Instant.getLong(Instant.java:603) ~[na:1.8.0_74]
	at java.time.format.DateTimePrintContext.getValue(DateTimePrintContext.java:298) ~[na:1.8.0_74]
	at java.time.format.DateTimeFormatterBuilder$NumberPrinterParser.format(DateTimeFormatterBuilder.java:2540) ~[na:1.8.0_74]
	at java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2179) ~[na:1.8.0_74]
	at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1746) ~[na:1.8.0_74]
	at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1720) ~[na:1.8.0_74]
	at org.thymeleaf.extras.java8time.util.TemporalFormattingUtils.formatDate(TemporalFormattingUtils.java:183) ~[thymeleaf-extras-java8time-3.0.1.RELEASE.jar:3.0.1.RELEASE]
	at org.thymeleaf.extras.java8time.util.TemporalFormattingUtils.format(TemporalFormattingUtils.java:72) ~[thymeleaf-extras-java8time-3.0.1.RELEASE.jar:3.0.1.RELEASE]
	at org.thymeleaf.extras.java8time.util.TemporalFormattingUtils.format(TemporalFormattingUtils.java:67) ~[thymeleaf-extras-java8time-3.0.1.RELEASE.jar:3.0.1.RELEASE]
	at org.thymeleaf.extras.java8time.expression.Temporals.format(Temporals.java:250) ~[thymeleaf-extras-java8time-3.0.1.RELEASE.jar:3.0.1.RELEASE]

```
And the test
```java
    @Test(expected = TemplateProcessingException.class)
    public void testFormatWithException() throws Exception {
        Instant now = Instant.now();
        temporals.format(now, "yyyy-MM-dd");
    }
```

**Comment by jmiguelsamper** [comment]
First of all, my apologies for the extremely late reply.

The issue was that the method

     #temporals.format(time, pattern)

may receive any kind of Temporal object for the time argument and any kind of pattern for the pattern argument and our code did not take that into account.

If a Temporal object with no time zone was used and, at the same time, a pattern including zoned values was used, the reported error happened.

We've modified the implementation of temporals.format(time, pattern) to include the default zoneId if it is not provided.

Fixed on 3.0.2-SNAPSHOT
